[build]
    command = "[[ $CI = true ]] && npx pnpm install -r --store-dir=node_modules/.pnpm-store && npm run typedoc && npm run docs"
[build.environment]
    NPM_FLAGS="--prefix=./bin/empty-project/"